import { colors } from "./config";

export const styles = {
  channelsWindow: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: "lightgrey",
    minHeight: "50vh",
    maxHeight: "50vh",
    // borderRadius: 30,
    // marginRight: -30,
    borderTopLeftRadius: 30,
    borderBottomLeftRadius: 30,
    marginTop: "5vh",
    borderColor: "lightgrey",
    borderWidth: 2,
    borderStyle: "solid",
    padding: 0,
    overflow: "hidden",
  },
  channelsHeaderSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: 15,
  },
  channelsDisplaySection: {
    display: "flex",
    flexGrow: 1,
    flexShrink: 1,
    flexDirection: "column",
    overflow: "scroll",
    padding: 15,
    backgroundColor: "white",
    // paddingLeft: 20,
    // paddingRight: 20,
  },
  chatWindow: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: colors.primary,
    height: "75vh",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderRadius: 30,
    marginTop: "5vh",
    overflow: "hidden",
    padding: 2,
  },
  chatWindowHeader: {
    display: "flex",
    alignItems: "center",
    paddingLeft: 15,
    paddingRight: 20,
    paddingTop: 20,
    paddingBottom: 20,
    backgroundColor: colors.primary,
  },
  brandLogoContainer: {
    width: 40,
    height: 35,
    borderRadius: 40,
    backgroundColor: "white",
  },
  headerRow: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    width: "100%",
  },
  headerText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 20,
    marginLeft: 10,
  },
  chatWindowBody: {
    display: "flex",
    flexGrow: 1,
    flexShrink: 1,
    flexDirection: "column-reverse",
    overflow: "scroll",
    padding: 15,
    backgroundColor: "white",
  },
  supportMessageContainer: {
    display: "flex",
    justifyContent: "flex-end",
    marginRight: 0,
  },
  supportMessageBox: {
    backgroundColor: colors.primary,
    marginTop: 10,
    padding: 10,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 6,
    maxWidth: "60%",
  },
  clientMessageContainer: {
    display: "flex",
    justifyContent: "flex-start",
    marginRight: 0,
  },
  clientMessageBox: {
    backgroundColor: "lightgrey",
    color: "white",
    marginTop: 10,
    padding: 10,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 6,
    maxWidth: "60%",
  },

  chatWindowFooter: {
    borderTop: "2px dotted red",
    display: "flex",
    alignItems: "center",
    paddingLeft: 30,
    paddingRight: 15,
    padding: 3,
  },
  messageInputContainer: {
    display: "flex",
    flexGrow: 1,
    flexShrink: 1,
    paddingLeft: 10,
    paddingRight: 10,
  },
  messageInput: {
    width: "100%",
    // textAlign: "center",
    fontSize: 16,
    outline: "none",
    padding: "12px",
    borderRadius: "12px",
    border: `2px solid transparent`,
    paddingRight: 20,
    height: 40,
  },
};
